name: Release

on:
  push:
    tags:
      - "v*" # This correctly listens for pushes to tags like 'v1.0.0' or 'v2.1'.
    branches: main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Add your build steps here...

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.zip
          generate_release_notes: true
          overwrite_files: true
