name: Release

on:
  push:
    branches:
      - workflow # Or your main release branch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false # Important for protected branches with @semantic-release/git

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Or your desired Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use a PAT with repo scope
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If publishing to npm
