name: Commit and Push Example

on:
  push:
    branches:
      - main

permissions:
  contents: write  # <-- explicitly allow writing to the repo

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # uses built-in token

      - name: Make a small change
        run: echo "Updated at $(date)" >> update-log.txt

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add update-log.txt
          git commit -m "Auto update log file"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
